server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://470556:glc_eyJvIjoiODM2MzgyIiwibiI6InN0YWNrLTYyMTE1Ny1lYXN5c3RhcnQtcHJvbS1wdWJsaXNoZXIiLCJrIjoiczM1N2xKTlkycWYwaXljOGE1VzB4OTZuIiwibSI6eyJyIjoicHJvZC11cy1lYXN0LTAifX0=@logs-prod-006.grafana.net/api/prom/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log